const products=[
{id:1,name:"Aero Smartwatch S2",category:"Tech",price:4999,old:6999,rating:4.8,icon:"⌚",badge:"BESTSELLER",desc:"A sleek everyday smartwatch with fitness tracking, notifications and a bright display."},
{id:2,name:"Studio Wireless Headphones",category:"Tech",price:6499,old:8999,rating:4.9,icon:"🎧",badge:"TOP RATED",desc:"Comfort-first wireless headphones designed for music, study and travel."},
{id:3,name:"Everyday Runner Sneakers",category:"Fashion",price:3299,old:4499,rating:4.7,icon:"👟",badge:"NEW",desc:"Lightweight everyday sneakers with a clean silhouette and cushioned feel."},
{id:4,name:"Minimal Carry Backpack",category:"Fashion",price:2799,old:3599,rating:4.6,icon:"🎒",badge:"POPULAR",desc:"A versatile backpack with smart storage for everyday essentials."},
{id:5,name:"Ceramic Desk Lamp",category:"Home",price:1899,old:2499,rating:4.5,icon:"💡",badge:"",desc:"Warm, minimal lighting for desks, bedside tables and cozy corners."},
{id:6,name:"Cloud Comfort Cushion",category:"Home",price:1299,old:1699,rating:4.8,icon:"🛋️",badge:"DEAL",desc:"Soft-touch cushion with a clean design that works across modern interiors."},
{id:7,name:"Hydro Steel Bottle",category:"Lifestyle",price:999,old:1399,rating:4.7,icon:"🥤",badge:"ECO PICK",desc:"Reusable insulated bottle for school, work, workouts and weekends."},
{id:8,name:"Daily Essentials Set",category:"Lifestyle",price:1599,old:2199,rating:4.6,icon:"🎁",badge:"VALUE",desc:"A practical bundle of useful everyday accessories."}
];
const categories=[["Tech","Smart devices & audio","💻"],["Fashion","Fresh everyday style","🧥"],["Home","Make space feel better","🏠"],["Lifestyle","Useful daily essentials","✨"]];
let cart=JSON.parse(localStorage.getItem("mypractice-cart")||"[]"), wishes=JSON.parse(localStorage.getItem("mypractice-wishes")||"[]");
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>"₹"+n.toLocaleString("en-IN");
function save(){localStorage.setItem("mypractice-cart",JSON.stringify(cart));localStorage.setItem("mypractice-wishes",JSON.stringify(wishes));updateCounts();}
function updateCounts(){$("#cartCount").textContent=cart.reduce((a,x)=>a+x.qty,0);$("#wishCount").textContent=wishes.length}
function renderCategories(){$("#categoryGrid").innerHTML=categories.map(c=>`<button class="category" data-cat="${c[0]}"><h3>${c[0]}</h3><p>${c[1]}</p><span class="cat-icon">${c[2]}</span></button>`).join("");$$(".category").forEach(b=>b.onclick=()=>{location.hash="shop";$("#categoryFilter").value=b.dataset.cat;renderProducts()})}
function renderFilters(){const cats=[...new Set(products.map(p=>p.category))];$("#categoryFilter").innerHTML='<option value="all">All categories</option>'+cats.map(c=>`<option>${c}</option>`).join("")}
function filtered(){let q=$("#searchInput").value.toLowerCase(),cat=$("#categoryFilter").value,max=+$("#priceFilter").value;let a=products.filter(p=>(!q||`${p.name} ${p.category}`.toLowerCase().includes(q))&&(cat==="all"||p.category===cat)&&p.price<=max);let sort=$("#sortSelect").value;if(sort==="price-low")a.sort((x,y)=>x.price-y.price);if(sort==="price-high")a.sort((x,y)=>y.price-x.price);if(sort==="rating")a.sort((x,y)=>y.rating-x.rating);return a}
function renderProducts(){const a=filtered();$("#productGrid").innerHTML=a.length?a.map(p=>`<article class="product-card"><div class="product-image"><span>${p.icon}</span>${p.badge?`<span class="badge">${p.badge}</span>`:""}<button class="wish ${wishes.includes(p.id)?"active":""}" data-wish="${p.id}">${wishes.includes(p.id)?"♥":"♡"}</button></div><div class="product-info"><h3>${p.name}</h3><div class="meta"><span>★ ${p.rating}</span><span>${p.category}</span></div><p class="price">${money(p.price)} <span class="old">${money(p.old)}</span></p><button class="add-btn" data-add="${p.id}">Add to cart</button></div></article>`).join(""):`<div class="empty" style="grid-column:1/-1">No products match your filters.</div>`;$$("[data-add]").forEach(b=>b.onclick=()=>add(+b.dataset.add));$$("[data-wish]").forEach(b=>b.onclick=()=>toggleWish(+b.dataset.wish));$$(".product-card").forEach((c,i)=>c.querySelector(".product-image span").onclick=()=>openProduct(a[i]))}
function add(id){let item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({id,qty:1});save();renderCart();toast("Added to your cart");}
function toggleWish(id){wishes=wishes.includes(id)?wishes.filter(x=>x!==id):[...wishes,id];save();renderProducts();toast(wishes.includes(id)?"Saved to wishlist":"Removed from wishlist")}
function renderCart(){if(!cart.length){$("#cartItems").innerHTML='<div class="empty">Your cart is empty.<br>Find something you love.</div>';$("#subtotal").textContent="₹0";return}let total=0;$("#cartItems").innerHTML=cart.map(x=>{let p=products.find(y=>y.id===x.id),t=p.price*x.qty;total+=t;return `<div class="cart-row"><div class="cart-art">${p.icon}</div><div><h4>${p.name}</h4><small>${money(p.price)}</small><div class="qty"><button data-dec="${p.id}">−</button><span>${x.qty}</span><button data-inc="${p.id}">+</button></div></div><button class="remove" data-remove="${p.id}">Remove</button></div>`}).join("");$("#subtotal").textContent=money(total);$$("[data-inc]").forEach(b=>b.onclick=()=>changeQty(+b.dataset.inc,1));$$("[data-dec]").forEach(b=>b.onclick=()=>changeQty(+b.dataset.dec,-1));$$("[data-remove]").forEach(b=>b.onclick=()=>removeItem(+b.dataset.remove))}
function changeQty(id,d){let x=cart.find(a=>a.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(a=>a.id!==id);save();renderCart()}
function removeItem(id){cart=cart.filter(x=>x.id!==id);save();renderCart()}
function openProduct(p){$("#modalContent").innerHTML=`<div class="product-detail"><div class="detail-art">${p.icon}</div><div class="detail-info"><span class="eyebrow">${p.category.toUpperCase()}</span><h2>${p.name}</h2><div>★★★★★ <span style="color:#777"> ${p.rating} customer rating</span></div><div class="big-price">${money(p.price)} <del style="font-size:13px;color:#aaa">${money(p.old)}</del></div><p style="color:#777;line-height:1.7">${p.desc}</p><button class="btn primary full" onclick="add(${p.id});closeModals()">Add to cart</button></div></div>`;$("#productModal").classList.add("open")}
function closeModals(){$$(".modal-backdrop").forEach(x=>x.classList.remove("open"))}
function toast(msg){$("#toast").textContent=msg;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),1800)}
function openCart(){$("#cartDrawer").classList.add("open");renderCart()}
function checkout(){if(!cart.length){toast("Your cart is empty");return}let total=cart.reduce((s,x)=>s+products.find(p=>p.id===x.id).price*x.qty,0);$("#checkoutSummary").innerHTML=cart.map(x=>{let p=products.find(y=>y.id===x.id);return `<div class="summary-row"><span>${p.name} × ${x.qty}</span><strong>${money(p.price*x.qty)}</strong></div>`}).join("");$("#checkoutTotal").textContent=money(total);$("#checkoutModal").classList.add("open")}
renderCategories();renderFilters();renderProducts();updateCounts();
$("#sortSelect").onchange=renderProducts;$("#categoryFilter").onchange=renderProducts;$("#priceFilter").oninput=e=>{$("#priceValue").textContent=e.target.value;renderProducts()};
$("#filterBtn").onclick=()=>$("#filterPanel").classList.toggle("open");$("#clearFilters").onclick=()=>{$("#categoryFilter").value="all";$("#priceFilter").value=50000;$("#priceValue").textContent=50000;renderProducts()};
$("#cartBtn").onclick=openCart;$("#accountBtn").onclick=()=>$("#accountModal").classList.add("open");$("#wishlistBtn").onclick=()=>{let ids=wishes.map(id=>products.find(p=>p.id===id)).filter(Boolean);$("#productGrid").innerHTML=ids.length?ids.map(p=>`<article class="product-card"><div class="product-image">${p.icon}<button class="wish active" onclick="toggleWish(${p.id})">♥</button></div><div class="product-info"><h3>${p.name}</h3><div class="meta"><span>★ ${p.rating}</span><span>${p.category}</span></div><p class="price">${money(p.price)}</p><button class="add-btn" onclick="add(${p.id})">Add to cart</button></div></article>`).join(""):'<div class="empty" style="grid-column:1/-1">Your wishlist is empty.</div>';location.hash="shop"};
$("#checkoutBtn").onclick=checkout;$("#placeOrder").onclick=()=>{if(!$("#checkoutName").value||!$("#checkoutEmail").value){toast("Please enter your name and email");return}cart=[];save();closeModals();$("#cartDrawer").classList.remove("open");toast("Demo order placed successfully 🎉");};
$$(".modal-close").forEach(b=>b.onclick=()=>{b.closest(".modal-backdrop")?.classList.remove("open");$("#cartDrawer").classList.remove("open")});
$$(".modal-backdrop").forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.remove("open")});
$("#mobileMenuBtn").onclick=()=>$("#mobileNav").classList.toggle("open");
$$("[data-scroll]").forEach(b=>b.onclick=()=>document.querySelector(b.dataset.scroll)?.scrollIntoView({behavior:"smooth"}));
$("#searchInput").oninput=()=>{renderProducts();let q=$("#searchInput").value.trim().toLowerCase(),box=$("#searchSuggestions");if(!q){box.style.display="none";return}let s=products.filter(p=>p.name.toLowerCase().includes(q)).slice(0,5);box.innerHTML=s.map(p=>`<div class="suggestion" data-suggest="${p.id}">${p.name}<span>${money(p.price)}</span></div>`).join("");box.style.display=s.length?"block":"none";$$("[data-suggest]").forEach(x=>x.onclick=()=>{openProduct(products.find(p=>p.id==x.dataset.suggest));box.style.display="none"})};
$("#newsletterForm").onsubmit=e=>{e.preventDefault();toast("You're on the list ✨");e.target.reset()};
let end=Date.now()+12*3600000+48*60000+32000;setInterval(()=>{let n=Math.max(0,end-Date.now()),h=Math.floor(n/3600000),m=Math.floor(n%3600000/60000),s=Math.floor(n%60000/1000);$("#hours").textContent=String(h).padStart(2,"0");$("#minutes").textContent=String(m).padStart(2,"0");$("#seconds").textContent=String(s).padStart(2,"0")},1000);
document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeModals();$("#cartDrawer").classList.remove("open")}});